--  Two ways to generate a pivot table

SELECT 
    DEPTNO,
    SUM(CASE WHEN JOB = 'ANALYST' THEN SAL ELSE 0 END) AS "ANALYST",
    SUM(CASE WHEN job = 'MANAGER' THEN sal ELSE 0 END) AS "MANAGER",
    SUM(CASE WHEN job = 'CLERK' THEN sal ELSE 0 END) AS "CLERK",
    SUM(CASE WHEN job = 'SALESMAN' THEN sal ELSE 0 END) AS "SALESMAN",
    SUM(CASE WHEN job = 'PRESIDENT' THEN sal ELSE 0 END) AS "PRESIDENT"
FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO 

-- OR

SELECT * FROM
(SELECT DEPTNO, JOB, SAL FROM EMP)
PIVOT (SUM(SAL) FOR JOB IN ('ANALYST', 'CLERK', 'SALESMAN', 'MANAGER', 'PRESIDENT'));